
INCLUDE_PATH=-I$(TOPDIR)/include 

LIB_PATH = $(TOPDIR)/lib
#TARGET defined if main in this dir
TARGET:=demo
CFLAGS = $(INCLUDE_PATH)
LDFLAGS := -L$(TOPDIR)/lib -lwilddog


include $(TOPDIR)/project/linux/env.mk
