

#if do not want built all dirs, use include_dirs and exclude_dirs.
# define the dirs your want built 
include_dirs:= $(PORT_TYPE)
# define the dirs you don not want built
exclude_dirs:=

include $(TOPDIR)/project/linux/env.mk

