
#INCLUDE_PATH=-I$(TOPDIR)/include -I$(TOPDIR)/src/include -I$(shell pwd)/inc
#LIB_PATH = $(TOPDIR)/lib 

#CFLAGS = $(INCLUDE_PATH)
#LDFLAGS += -L$(shell pwd)/lib -lmbedtls

exclude_dirs= inc 

include $(TOPDIR)/env.mk
