/*
 * wilddog_config.h
 *
 *  Created on: 2015年3月12日
 *      Author: x
 */

#ifndef __WILDDOG_CONFIG_H_
#define __WILDDOG_CONFIG_H_

#define WILDDOG_HOST_SUFFIX ".io.wilddog.com"

#define COAP_DEBUG_FD stdout
#define COAP_MAX_SIZE 1280
#define MAX_PATH_LEN 256;
#define WILDDOG_SERVER_PORT 5683
#define WILDDOG_BUF_SIZE 1024

#define WILDDOG_LOOP_PER_SECOND 100
#define WILDDOG_RECV_TIMEOUT 10
#define WILDDOG_OBSERVE_TIMEOUT 0

#define WILDDOG_CODE_MALLOC_ERROR -1
#define WILDDOG_CODE_FREE_ERROR -2
#define WILDDOG_CODE_NO_ALIVE_SOCKET -10
#define WILDDOG_CODE_SENDERROR -11
#define WILDDOG_CODE_JSON_PARSE_ERROR -20
#define WILDDOG_CODE_JSON_STRINGIFY_ERROR -30
#define WILDDOG_CODE_COAP_PARSE_ERROR -40
#define WILDDOG_CODE_COAP_TOBUF_ERROR -50
#define WILDDOG_CODE_TIMEOUT -60;

#define WILDDOG_CODE_NO_NEWKEY_RETURNED -70

#endif /* WILDDOG_CONFIG_H_ */
